name: bonfire
description: Bonfire is a modern social app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+9

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  background_fetch: ^0.6.0
  bloc: ^5.0.0
  cached_network_image: ^2.2.0+1
  camera: ^0.5.8+2
  circular_profile_avatar: ^1.0.6
  cloud_firestore: ^0.13.7
  color_thief_flutter: ^1.0.2
  dependency_validator: ^1.5.0
  device_info: ^0.4.2+4
  devicelocale: ^0.2.3
  downloads_path_provider: ^0.1.0
  equatable: ^1.2.0
  extended_image: ^0.9.0
  file_picker: ^1.12.0
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  flushbar: ^1.10.4
  flutter_bloc: ^5.0.0
  flutter_downloader: ^1.4.4
  flutter_email_sender: ^3.0.1
  flutter_icons: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  freezed_annotation: ^0.11.0
  geoflutterfire: ^2.1.0
  geolocator: ^5.3.2+2
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  image_picker: ^0.6.7+3
  jiffy: ^3.0.1
  logger: ^0.9.1
  mapbox_gl: ^0.7.0
  mime: ^0.9.6+3
  package_info: ^0.4.1
  password: ^1.0.0
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  rounded_modal: ^1.0.1
  sailor: ^0.7.1
  sliding_up_panel: ^1.0.2
  stringprocess: ^1.0.10
  time: ^1.3.0
  timeago: ^2.0.26
  uuid: ^2.1.0
  video_player: ^0.10.11+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dependency_overrides:
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  flappy_translator: ^1.2.2
  flutter_launcher_icons: ^0.7.5
  freezed: ^0.11.2
  hive_generator: ^0.7.0+2
  lint: ^1.2.0

flappy_translator:
  input_file_path: "locales/locales.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ","
  start_index: 1
  depend_on_context: true
  use_single_quotes: false
  replace_no_break_spaces: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/skins/default/
    - assets/img/
    - assets/cache.db
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #   - family: VarelaRound
  #     fonts:
  #       - asset: assets/fonts/VarelaRound-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
