import 'dart:async';

import 'package:flutter/material.dart';

/// This class is generated by the flappy_translator package
/// Please do not change anything manually in this file, instead re-generate it when changes are available
class I18n {
  String get buttonCancel => _getText("buttonCancel");

  String get buttonDownload => _getText("buttonDownload");

  String get buttonDownloadFile => _getText("buttonDownloadFile");

  String get buttonFollow => _getText("buttonFollow");

  String get buttonFollowing => _getText("buttonFollowing");

  String get buttonImSure => _getText("buttonImSure");

  String get buttonLight => _getText("buttonLight");

  String get buttonNext => _getText("buttonNext");

  String get buttonSelectFile => _getText("buttonSelectFile");

  String get buttonSendResetLink => _getText("buttonSendResetLink");

  String get buttonSignAnonymous => _getText("buttonSignAnonymous");

  String get buttonSignIn => _getText("buttonSignIn");

  String get buttonSignUp => _getText("buttonSignUp");

  String get buttonUpdateMy => _getText("buttonUpdateMy");

  String get connectionProblem => _getText("connectionProblem");

  String get sendEmailFailed => _getText("sendEmailFailed");

  String get sendingLink => _getText("sendingLink");

  String get sentLink => _getText("sentLink");

  String get signGoogle => _getText("signGoogle");

  String get start => _getText("start");

  String get textAcceptOurTerms => _getText("textAcceptOurTerms");

  String get textAcceptOurTermsAlt => _getText("textAcceptOurTermsAlt");

  String get textAccessProfile => _getText("textAccessProfile");

  String get textAccountActions => _getText("textAccountActions");

  String get textAndOur => _getText("textAndOur");

  String get textAnonymousDisclaimer1 => _getText("textAnonymousDisclaimer1");

  String get textAnonymousDisclaimer2 => _getText("textAnonymousDisclaimer2");

  String get textAnonymousDisclaimer3 => _getText("textAnonymousDisclaimer3");

  String get textAnonymousLoggingIn => _getText("textAnonymousLoggingIn");

  String get textAppName => _getText("textAppName");

  String get textAuthenticating => _getText("textAuthenticating");

  String get textAuthenticationFailed => _getText("textAuthenticationFailed");

  String get textBonfireLit => _getText("textBonfireLit");

  String get textBonfirePlaceholder => _getText("textBonfirePlaceholder");

  String get textClearCache => _getText("textClearCache");

  String get textCompleted => _getText("textCompleted");

  String get textCompleteProfile => _getText("textCompleteProfile");

  String get textConfirmNewPassword => _getText("textConfirmNewPassword");

  String get textConfirmPassword => _getText("textConfirmPassword");

  String get textContinueAnonymous => _getText("textContinueAnonymous");

  String get textConvertingAccount => _getText("textConvertingAccount");

  String get textCurrentPassword => _getText("textCurrentPassword");

  String get textDailyQuest => _getText("textDailyQuest");

  String get textDarkMode => _getText("textDarkMode");

  String get textDeadline => _getText("textDeadline");

  String get textDownloading => _getText("textDownloading");

  String get textDownloadManager => _getText("textDownloadManager");

  String get textEditingProfilePicture => _getText("textEditingProfilePicture");

  String get textEditProfilePicture => _getText("textEditProfilePicture");

  String get textEmail => _getText("textEmail");

  String get textEmailUpdated => _getText("textEmailUpdated");

  String get textErrorDownload => _getText("textErrorDownload");

  String get textErrorLightingBonfire => _getText("textErrorLightingBonfire");

  String get textErrorOccured => _getText("textErrorOccured");

  String get textErrorRecording => _getText("textErrorRecording");

  String get textExperience => _getText("textExperience");

  String get textFailedLoadContent => _getText("textFailedLoadContent");

  String get textFeebackDisclaimer => _getText("textFeebackDisclaimer");

  String get textFeebackHint => _getText("textFeebackHint");

  String get textFile => _getText("textFile");

  String get textFileDownloaded => _getText("textFileDownloaded");

  String get textFiles => _getText("textFiles");

  String get textFollowing => _getText("textFollowing");

  String get textFollowingLimitReached => _getText("textFollowingLimitReached");

  String get textForgotPassword => _getText("textForgotPassword");

  String get textGiveFeedback => _getText("textGiveFeedback");

  String get textHaveAccount => _getText("textHaveAccount");

  String get textImage => _getText("textImage");

  String get textInitializing => _getText("textInitializing");

  String get textInitializingParameters =>
      _getText("textInitializingParameters");

  String get textInProgress => _getText("textInProgress");

  String get textInvalidConfirmPassword =>
      _getText("textInvalidConfirmPassword");

  String get textInvalidEmail => _getText("textInvalidEmail");

  String get textInvalidName => _getText("textInvalidName");

  String get textInvalidPassword => _getText("textInvalidPassword");

  String get textInvalidProvidedPassword =>
      _getText("textInvalidProvidedPassword");

  String get textInvalidUsername => _getText("textInvalidUsername");

  String get textLightBonfire => _getText("textLightBonfire");

  String get textLoggingOut => _getText("textLoggingOut");

  String get textLogout => _getText("textLogout");

  String get textMoreInfo => _getText("textMoreInfo");

  String get textMyAccount => _getText("textMyAccount");

  String get textMyBonfires => _getText("textMyBonfires");

  String get textMyData => _getText("textMyData");

  String get textMyFollowing => _getText("textMyFollowing");

  String get textMyTrophies => _getText("textMyTrophies");

  String get textName => _getText("textName");

  String get textNameUpdated => _getText("textNameUpdated");

  String get textNewEmailAddress => _getText("textNewEmailAddress");

  String get textNewName => _getText("textNewName");

  String get textNewPassword => _getText("textNewPassword");

  String get textNothingHere => _getText("textNothingHere");

  String get textNotImplementedYet => _getText("textNotImplementedYet");

  String get textPassword => _getText("textPassword");

  String get textPasswordUpdated => _getText("textPasswordUpdated");

  String get textPenalty => _getText("textPenalty");

  String get textPenaltyDescription => _getText("textPenaltyDescription");

  String get textPermissionDenied => _getText("textPermissionDenied");

  String get textPermissionRequest => _getText("textPermissionRequest");

  String get textPermissions => _getText("textPermissions");

  String get textPrivacy => _getText("textPrivacy");

  String get textPrivacyPolicy => _getText("textPrivacyPolicy");

  String get textPrivacyPolicyContent => _getText("textPrivacyPolicyContent");

  String get textProfilePicture => _getText("textProfilePicture");

  String get textQuestDirections => _getText("textQuestDirections");

  String get textQuestionMark => _getText("textQuestionMark");

  String get textReportProblem => _getText("textReportProblem");

  String get textReportProblemDisclaimer =>
      _getText("textReportProblemDisclaimer");

  String get textReportProblemHint => _getText("textReportProblemHint");

  String get textResetLinkSent => _getText("textResetLinkSent");

  String get textResetPasswordLink => _getText("textResetPasswordLink");

  String get textRetrieveBonfires => _getText("textRetrieveBonfires");

  String get textRetrieveDeviceData => _getText("textRetrieveDeviceData");

  String get textRetrieveUserData => _getText("textRetrieveUserData");

  String get textSave => _getText("textSave");

  String get textSavingProfile => _getText("textSavingProfile");

  String get textSettings => _getText("textSettings");

  String get textStatus => _getText("textStatus");

  String get textStore => _getText("textStore");

  String get textSuccessInitialized => _getText("textSuccessInitialized");

  String get textSupport => _getText("textSupport");

  String get textSureLogout => _getText("textSureLogout");

  String get textSureModify => _getText("textSureModify");

  String get textTaskManager => _getText("textTaskManager");

  String get textTermsOfService => _getText("textTermsOfService");

  String get textTermsOfServiceContent => _getText("textTermsOfServiceContent");

  String get textText => _getText("textText");

  String get textThanksFeedback => _getText("textThanksFeedback");

  String get textThanksReportProblem => _getText("textThanksReportProblem");

  String get textTotal => _getText("textTotal");

  String get textTranslationManager => _getText("textTranslationManager");

  String get textUpdateMyEmail => _getText("textUpdateMyEmail");

  String get textUpdateMyName => _getText("textUpdateMyName");

  String get textUpdateMyPassword => _getText("textUpdateMyPassword");

  String get textUpdatingEmail => _getText("textUpdatingEmail");

  String get textUpdatingName => _getText("textUpdatingName");

  String get textUpdatingPassword => _getText("textUpdatingPassword");

  String get textUsername => _getText("textUsername");

  String get textVideo => _getText("textVideo");

  String get textWarning => _getText("textWarning");

  String get textWarningDescription1 => _getText("textWarningDescription1");

  String get userEmailNotFound => _getText("userEmailNotFound");

  static Map<String, String> _localizedValues;

  static final Map<String, String> _enValues = {
    "buttonCancel": "Cancel",
    "buttonDownload": "Download",
    "buttonDownloadFile": "Download the file",
    "buttonFollow": "Follow",
    "buttonFollowing": "Following",
    "buttonImSure": "I'm sure",
    "buttonLight": "Light",
    "buttonNext": "Next",
    "buttonSelectFile": "Choose a file",
    "buttonSendResetLink": "Send recovery link",
    "buttonSignAnonymous": "Start Anonymously",
    "buttonSignIn": "Login",
    "buttonSignUp": "Create an account",
    "buttonUpdateMy": "Update my",
    "connectionProblem": "Trouble logging in?",
    "sendEmailFailed": "Sending the confirmation email failed",
    "sendingLink": "We send you an email with a confirmation link",
    "sentLink": "We sent you an email with a confirmation link",
    "signGoogle": "Sign in with Google",
    "start": "Let's go",
    "textAcceptOurTerms": "By logging in you accept our ",
    "textAcceptOurTermsAlt":
        "By creating an account and/or logging in you accept our ",
    "textAccessProfile":
        "To access the user profile, you need to create a permanent account or log in with an existing account!",
    "textAccountActions": "Account actions",
    "textAndOur": " and our ",
    "textAnonymousDisclaimer1":
        "By logging in anonymously you will not have access to the following features",
    "textAnonymousDisclaimer2": "- A user profile",
    "textAnonymousDisclaimer3": "- Bonfire rating",
    "textAnonymousLoggingIn": "We're connecting you, please wait...",
    "textAppName": "Bonfire",
    "textAuthenticating": "Authentication in progress...",
    "textAuthenticationFailed": "Authentication failure",
    "textBonfireLit": "Bonfires lit",
    "textBonfirePlaceholder": "What's on your mind today?",
    "textClearCache": "Clear the cache",
    "textCompleted": "completed",
    "textCompleteProfile": "Complete your profile",
    "textConfirmNewPassword": "Confirm your new password",
    "textConfirmPassword": "Confirm your password",
    "textContinueAnonymous": "Continue anonymously? ",
    "textConvertingAccount":
        "Anonymous account conversion in progress, please wait...",
    "textCurrentPassword": "Current password",
    "textDailyQuest": "Daily Quest",
    "textDarkMode": "Dark Mode",
    "textDeadline": "Deadline",
    "textDownloading": "The download has started, please wait...",
    "textDownloadManager": "Download Manager",
    "textEditingProfilePicture":
        "We're updating your profile picture, please wait...",
    "textEditProfilePicture": "Edit my profile picture",
    "textEmail": "E-mail address",
    "textEmailUpdated": "Your e-mail address has been updated!",
    "textErrorDownload":
        "An error occurred during the download, try again later.",
    "textErrorLightingBonfire": "Sorry we didn't get to light your bonfire",
    "textErrorOccured": "An error has occurred",
    "textErrorRecording": "Something went wrong during the recording",
    "textExperience": "Experience",
    "textFailedLoadContent": "Failed to load content",
    "textFeebackDisclaimer":
        "This page allows you to give your opinion on the app, suggest ideas for features and/or changes. If you want to report a problem with the app, use the dedicated page instead.",
    "textFeebackHint": "What do you want to tell us?",
    "textFile": "File",
    "textFileDownloaded": "File downloaded",
    "textFiles": "File(s)",
    "textFollowing": "Following",
    "textFollowingLimitReached":
        "You've reached the limit of the number of following",
    "textForgotPassword": "Forgot your password?",
    "textGiveFeedback": "Give feedback",
    "textHaveAccount": "I already have an account/I want to create an account",
    "textImage": "Image",
    "textInitializing": "Initializing",
    "textInitializingParameters":
        "Initialization of minor parameters in progress...",
    "textInProgress": "in progress",
    "textInvalidConfirmPassword": "Passwords must be the same",
    "textInvalidEmail": "Invalid e-mail address",
    "textInvalidName": "The name must not be null or empty",
    "textInvalidPassword":
        "The password must be at least 8 characters long and must include at least\n1 lowercase,\n1 uppercase,\n1 digit\n1 special character",
    "textInvalidProvidedPassword": "The password provided is invalid",
    "textInvalidUsername": "The username must not be null or empty",
    "textLightBonfire": "Light a bonfire",
    "textLoggingOut": "Logging out...",
    "textLogout": "Logout",
    "textMoreInfo": "More information",
    "textMyAccount": "My account",
    "textMyBonfires": "My bonfires",
    "textMyData": "My data",
    "textMyFollowing": "My following",
    "textMyTrophies": "My trophies",
    "textName": "Name",
    "textNameUpdated": "Your name has been updated!",
    "textNewEmailAddress": "New e-mail address",
    "textNewName": "New name",
    "textNewPassword": "New password",
    "textNothingHere": "Nothing to see here",
    "textNotImplementedYet":
        "This feature has not yet been implemented, stay tuned, it will come with future updates.",
    "textPassword": "Password",
    "textPasswordUpdated": "Your password has been updated!",
    "textPenalty": "Penalty",
    "textPenaltyDescription": "Description of the penalty",
    "textPermissionDenied": "An application for authorization was rejected.",
    "textPermissionRequest":
        "Applications for authorizations are in progress...",
    "textPermissions": "Permissions",
    "textPrivacy": "Privacy",
    "textPrivacyPolicy": "Privacy Policy",
    "textPrivacyPolicyContent":
        "We don't have a privacy policy yet, we do our best to make it available to our users as soon as possible.",
    "textProfilePicture": "Profile picture",
    "textQuestDirections": "Quest directions",
    "textQuestionMark": "?",
    "textReportProblem": "Report a problem",
    "textReportProblemDisclaimer":
        "Additional information about the device will be sent to enable us to solve the problem as soon as possible",
    "textReportProblemHint": "What problem did you run into?",
    "textResetLinkSent": "A recovery link has been sent to your email address.",
    "textResetPasswordLink":
        "A recovery link will be sent to your email address",
    "textRetrieveBonfires": "Retrieve bonfires",
    "textRetrieveDeviceData":
        "Retrieving information on the current device, please wait...",
    "textRetrieveUserData": "Retrieving user information, please wait...",
    "textSave": "Save",
    "textSavingProfile": "Saving the profile, please wait...",
    "textSettings": "Settings",
    "textStatus": "Status",
    "textStore": "Store",
    "textSuccessInitialized": "Successfully initialized",
    "textSupport": "Support",
    "textSureLogout": "Are you sure you want to logout?",
    "textSureModify": "Are you sure you want to change your",
    "textTaskManager": "Task Manager",
    "textTermsOfService": "Terms of Services",
    "textTermsOfServiceContent":
        "We do not yet have general terms and conditions of use, we do our best to make them available to our users as soon as possible.",
    "textText": "Text",
    "textThanksFeedback":
        "Thank you for your feedback, we'll do our best to make good use of it",
    "textThanksReportProblem":
        "The problem has been reported, we'll do our best to solve it",
    "textTotal": "Total",
    "textTranslationManager": "Translation Manager",
    "textUpdateMyEmail": "Update my e-mail address",
    "textUpdateMyName": "Update my name",
    "textUpdateMyPassword": "Update my password",
    "textUpdatingEmail": "Updating your e-mail address, please wait...",
    "textUpdatingName": "Updating your name, please wait...",
    "textUpdatingPassword": "Updating your password, please wait...",
    "textUsername": "Username",
    "textVideo": "Video",
    "textWarning": "Warning",
    "textWarningDescription1":
        "the failure of this daily quest will result in a penalty",
    "userEmailNotFound":
        "We couldn't find any accounts associated with this email",
  };

  static final Map<String, String> _frValues = {
    "buttonCancel": "Annuler",
    "buttonDownload": "Télécharger",
    "buttonDownloadFile": "Télécharger le fichier",
    "buttonFollow": "S'abonner",
    "buttonFollowing": "Abonné",
    "buttonImSure": "Je suis sûre",
    "buttonLight": "Allumer",
    "buttonNext": "Continuer",
    "buttonSelectFile": "Sélectionner un fichier",
    "buttonSendResetLink": "Envoyer le lien de récupération",
    "buttonSignAnonymous": "Commencer Anonymement",
    "buttonSignIn": "Se connecter",
    "buttonSignUp": "Créer un compte",
    "buttonUpdateMy": " Mettre à jour mon",
    "connectionProblem": "Problème de connexion ?",
    "sendEmailFailed": "L'envoi de l'email de confirmation a échoué",
    "sendingLink": "Nous t'envoyons un email contenant un lien de confirmation",
    "sentLink":
        "Nous t'avons envoyé un email contenant un lien de confirmation",
    "signGoogle": "Se connecter via Google",
    "start": "C'est parti",
    "textAcceptOurTerms": "En te connectant tu acceptes nos ",
    "textAcceptOurTermsAlt":
        "En créant un compte et/ou en te connectant tu acceptes nos ",
    "textAccessProfile":
        "Pour accéder au profil utilisateur, tu dois créer un compte permanent ou te connecter avec un compte existant !",
    "textAccountActions": "Actions de compte",
    "textAndOur": " et notre ",
    "textAnonymousDisclaimer1":
        "En te connectant anonymement tu n'auras pas accés aux fonctionnalités suivantes",
    "textAnonymousDisclaimer2": "- Un profil utilisateur",
    "textAnonymousDisclaimer3": "- La notation des feux de camp",
    "textAnonymousLoggingIn": "Nous te connectons, un peu de patience...",
    "textAppName": "Bonfire",
    "textAuthenticating": "Authentification en cours...",
    "textAuthenticationFailed": "Echec de l'authentification",
    "textBonfireLit": "Feux de camp allumés",
    "textBonfirePlaceholder": "Qu'as-tu en tête aujourd'hui ?",
    "textClearCache": "Vider le cache",
    "textCompleted": "complétée",
    "textCompleteProfile": "Complète ton profil",
    "textConfirmNewPassword": "Confirme ton nouveau mot de passe",
    "textConfirmPassword": "Confirme ton mot de passe",
    "textContinueAnonymous": "Continuer anonymement ?",
    "textConvertingAccount":
        "Convertion du compte anonyme en cours, un peu de patience...",
    "textCurrentPassword": "Mot de passe actuel",
    "textDailyQuest": "Quête journalière",
    "textDarkMode": "Mode Nuit",
    "textDeadline": "Échéance",
    "textDownloading": "Le téléchargement à commencé, un peu de patience...",
    "textDownloadManager": "Gestionnaire de téléchargements",
    "textEditingProfilePicture":
        "Nous mettons à jours ta photo de profil, un peu de patience...",
    "textEditProfilePicture": "Modifier ma photo de profil",
    "textEmail": "Adresse e-mail",
    "textEmailUpdated": "Ton adresse e-mail a été mis à jour !",
    "textErrorDownload":
        "Une erreur est survenue durant le téléchargement, réessaies plus tard.",
    "textErrorLightingBonfire":
        "Désolé, nous n'avons pas pu allumer ton feu de camp",
    "textErrorOccured": "Une erreur est survenue",
    "textErrorRecording": "Quelque chose a mal tourné pendant l'enregistrement",
    "textExperience": "Expérience",
    "textFailedLoadContent": "Échec du chargement du contenu",
    "textFeebackDisclaimer":
        "Cette page te permet de donner ton avis sur l'appli, proposer des idées de fonctionnalités et/ou des changements. Si tu veux signaler un problème sur l'appli, utilise plutôt la page dédiée.",
    "textFeebackHint": "Que veux-tu nous dire ?",
    "textFile": "Fichier",
    "textFileDownloaded": "Fichier téléchargé",
    "textFiles": "Fichier(s)",
    "textFollowing": "Abonné",
    "textFollowingLimitReached":
        "Tu as atteint la limite du nombre d'abonnement",
    "textForgotPassword": "Mot de passe oublié ?",
    "textGiveFeedback": "Donner un avis",
    "textHaveAccount": "J'ai déjà un compte/Je veux créer un compte",
    "textImage": "Image",
    "textInitializing": "Initialisation",
    "textInitializingParameters":
        "Initialisation de paramètres mineurs en cours...",
    "textInProgress": "en cours",
    "textInvalidConfirmPassword": "Les mots de passe doivent être les mêmes",
    "textInvalidEmail": "Addrese e-mail invalide",
    "textInvalidName": "Le nom ne doit pas être nul ou vide",
    "textInvalidPassword":
        "Le mot de passe doit contenir au minimum 8 caractères et doit inclure au moins\n1 minuscule,\n1 majuscule,\n1 chiffre\n1 caractére spécial",
    "textInvalidProvidedPassword": "Le mot de passe fournie est invalide",
    "textInvalidUsername": "e nom d'utilisateur ne doit pas être nul ou vide",
    "textLightBonfire": "Allumer un feu de camp",
    "textLoggingOut": "Déconnexion en cours...",
    "textLogout": "Déconnexion",
    "textMoreInfo": "Plus d'information",
    "textMyAccount": "Mon compte",
    "textMyBonfires": "Mes feux de camp",
    "textMyData": "Mes données",
    "textMyFollowing": "Mes abonnements",
    "textMyTrophies": "Mes trophées",
    "textName": "Nom",
    "textNameUpdated": "Ton nom a été mis à jour !",
    "textNewEmailAddress": "Nouvelle adresse e-mail",
    "textNewName": "Nouveau nom",
    "textNewPassword": "Nouveau mot de passe",
    "textNothingHere": "Rien à voir ici",
    "textNotImplementedYet":
        "Cette fonctionnalité n'a pas encore été implémentée, reste à l'écoute, elle sera disponible avec les futures mises à jour.",
    "textPassword": "Mot de passe",
    "textPasswordUpdated": "Ton mot de passe a été mis à jour !",
    "textPenalty": "Sanction",
    "textPenaltyDescription": "Description de la sanction",
    "textPermissionDenied": "Une demande d'autorisation a été rejetée.",
    "textPermissionRequest": "Les demandes d'autorisations sont en cours...",
    "textPermissions": "Autorisations",
    "textPrivacy": "Confidentialité",
    "textPrivacyPolicy": "Politique de confidentialité",
    "textPrivacyPolicyContent":
        "Nous n'avons pas encore de politique de confidentialité, nous faisons de notre mieux pour les mettres à disposition de nos utilisateurs au plus vite.",
    "textProfilePicture": "Photo de profil",
    "textQuestDirections": "Instructions de quête",
    "textQuestionMark": " ?",
    "textReportProblem": "Signaler un problème",
    "textReportProblemDisclaimer":
        "Des informations complémentaires concernant l'appareil seront envoyées pour nous permettre de résoudre le problème au plus vite",
    "textReportProblemHint": "Quel problème as-tu rencontré ?",
    "textResetLinkSent":
        "Un lien de récupération a été envoyé à votre adresse e-mail.",
    "textResetPasswordLink":
        "Un lien de récupération va t'etre envoyé sur ton adresse e-mail",
    "textRetrieveBonfires": "Récupérer les feux de camp",
    "textRetrieveDeviceData":
        "Récupération des informations sur l'appareil en cours, un peu de patience...",
    "textRetrieveUserData":
        "Récupération des informations sur l'utilisateur, un peu de patience...",
    "textSave": "Enregistrer",
    "textSavingProfile": "Sauvegarde du profil en cours, un peu de patience...",
    "textSettings": "Paramètres",
    "textStatus": "Statut",
    "textStore": "Boutique",
    "textSuccessInitialized": "Initialisé avec succès",
    "textSupport": "Assistance",
    "textSureLogout": "Es-tu sûre de vouloir te déconnecter ?",
    "textSureModify": "Es-tu sûre de vouloir modifier ton",
    "textTaskManager": "Gestionnaire de tâches",
    "textTermsOfService": "Conditions générales d'utilisation",
    "textTermsOfServiceContent":
        "Nous n'avons pas encore de conditions générales d'utilisation, nous faisons de notre mieux pour les mettres à disposition de nos utilisateurs au plus vite.",
    "textText": "Texte",
    "textThanksFeedback":
        "Merci pour ton feedback, nous ferons au mieux pour en faire bonne usage",
    "textThanksReportProblem":
        "Le problème as été signalé, nous ferons au mieux pour le résoudre",
    "textTotal": "Total",
    "textTranslationManager": "Gestionnaire de traductions",
    "textUpdateMyEmail": "Mettre à jour mon adresse e-mail",
    "textUpdateMyName": "Mettre à jour mon nom",
    "textUpdateMyPassword": "Mettre à jour mon mot de passe",
    "textUpdatingEmail": "Mise à jour de ton adresse e-mail en cours...",
    "textUpdatingName": "Mise à jour de ton nom en cours...",
    "textUpdatingPassword": "Mise à jour de ton mot de passe en cours...",
    "textUsername": "Nom d'utilisateur",
    "textVideo": "Vidéo",
    "textWarning": "Avertissement",
    "textWarningDescription1":
        "l'échec de cette quête quotidienne entrainera une sanction",
    "userEmailNotFound": "Nous n'avons trouvé aucun compte associé à cet email",
  };

  static final Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "fr": _frValues,
  };

  I18n(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  Locale _locale;

  static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }

  String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    const Locale('en'),
    const Locale('fr'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}
